call pathogen#infect()
call pathogen#helptags()
syntax on
filetype plugin indent on
colorscheme dracula
set number
set ttymouse=xterm2
set mouse=a
set t_Co=256
set background=dark
highlight Normal ctermbg=NONE
nnoremap <C-y> "+y
vnoremap <C-y> "+y
nnoremap <C-p> "+gP
vnoremap <C-p> "+gP
